code: 131172
gijiroku: data/gijiroku.csv
giin: data/giin.csv
iinkai: data/iinkai.csv
years: data/years.csv
jogai: data/exclusion.csv
font: static/ShipporiMinchoB1-ExtraBold.ttf
target:
  place: 北区
  start: 1991年3月
  end: 2022年10月
  url: https://www.city.kita.tokyo.jp/gikaijimukyoku/kuse/gikai/kaigiroku.html
developer:
  name: 岡村健一
  contact: https://twitter.com/Okamura_Kenichi
  img: static/developer.png